# Shared colour tokens for Hyprland (borders, shadows, indicators).
# Generic semantic names; see theme/colors.env for the role each maps to.

$bg           = rgb(@BG@)
$bg_alt       = rgb(@BG_ALT@)
$bg_deep      = rgb(@BG_DEEP@)
$surface0     = rgb(@SURFACE0@)
$surface1     = rgb(@SURFACE1@)
$surface2     = rgb(@SURFACE2@)
$fg           = rgb(@FG@)
$fg_dim       = rgb(@FG_DIM@)
$fg_faint     = rgb(@FG_FAINT@)
$muted        = rgb(@MUTED@)
$border       = rgb(@BORDER@)
$accent       = rgb(@ACCENT@)
$accent_dim   = rgb(@ACCENT_DIM@)
$accent_alt   = rgb(@ACCENT_ALT@)
$success      = rgb(@SUCCESS@)
$warning      = rgb(@WARNING@)
$error        = rgb(@ERROR@)
